services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_dbname
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  chromadb:
    image: chromadb/chroma:0.6.4.dev19
    container_name: chromadb
    ports:
      - "8001:8000"
    environment:
      IS_PERSISTENT: "TRUE"
      ANONYMIZED_TELEMETRY: "TRUE"
    volumes:
      - ./chroma_data:/chroma/chroma
volumes:
  pgdata:
